set pages 0
set long 1000000
spool ../out/cp_control.out

SELECT DBMS_XMLGEN.getXML ( 
'SELECT I.HOST_NAME, 
       	D.NAME DATABASE_NAME, 
	I.INSTANCE_NAME,
	I.INSTANCE_NUMBER,
	S.SNAP_ID,
	S.BEGIN_INTERVAL_TIME,
	S.END_INTERVAL_TIME,
	S.STARTUP_TIME
FROM	V$INSTANCE I,
	V$DATABASE D,
	DBA_HIST_SNAPSHOT S
WHERE	S.INSTANCE_NUMBER = I.INSTANCE_NUMBER
AND	S.END_INTERVAL_TIME > (sysdate - 1/24)
-- AND	trunc(S.END_INTERVAL_TIME,''HH24'') = ''18-NOV-14 23:00:00'''
)
FROM DUAL;

spool off
