set pages 0
set long 1000000
spool ../out/cp_ora_iostat_filetype.out

SELECT  DBMS_XMLGEN.GETXML ( 
'SELECT 	I.HOST_NAME,
	D.NAME	DATABASE_NAME,
	I.INSTANCE_NAME,
	I.INSTANCE_NUMBER,
	S.SNAP_ID,
	S.BEGIN_INTERVAL_TIME,
	S.END_INTERVAL_TIME,
	O.FILENAME,
	O.PHYRDS,
	O.READTIM,
	O.PHYWRTS,
	O.WRITETIM
FROM	V$INSTANCE I,
	V$DATABASE D,
	DBA_HIST_SNAPSHOT S,
	DBA_HIST_FILESTATXS O
WHERE 	S.SNAP_ID = O.SNAP_ID
AND 	S.INSTANCE_NUMBER = O.INSTANCE_NUMBER
AND	S.INSTANCE_NUMBER = I.INSTANCE_NUMBER
AND	S.END_INTERVAL_TIME > (SYSDATE - 1/24)'
) FROM DUAL;

spool off
